CREATE ROLE RT_BACKUP_ROLE;

-- role to checkup sap hana status
CREATE ROLE RT_MONITOR_ROLE; 

-- role to access, use and manage hana cockpit
CREATE ROLE RT_COCKPIT_ROLE;

-- role to access and manage repository
CREATE ROLE RT_REPOSITORY_ROLE; 

-- role to manage system and tenant databases
CREATE ROLE RT_SYSTEM_ROLE; 

-- Final role which gather all or some of the created roles
CREATE ROLE RT_ADMINISTRATOR_ROLE; 

--Which privileges to assign to sap hana administrator users?

/* BACKUP privileges
SQL Syntax */

GRANT BACKUP ADMIN TO RT_BACKUP_ROLE; 
GRANT CATALOG READ TO RT_BACKUP_ROLE; 

/* MONITOR privileges
SQL Syntax */

GRANT MONITORING TO RT_MONITOR_ROLE;

/* COCKPIT privileges
SQL Syntax */

GRANT TENANT ADMIN TO RT_COCKPIT_ROLE;
GRANT MONITORING TO RT_COCKPIT_ROLE;
GRANT BACKUP ADMIN TO RT_COCKPIT_ROLE;
GRANT CATALOG READ TO RT_COCKPIT_ROLE;
GRANT INIFILE ADMIN	TO RT_COCKPIT_ROLE;
GRANT SERVICE ADMIN TO RT_COCKPIT_ROLE;
GRANT TRACE ADMIN	TO RT_COCKPIT_ROLE;
GRANT RESOURCE ADMIN	TO RT_COCKPIT_ROLE;
GRANT LICENSE ADMIN TO RT_COCKPIT_ROLE;

GRANT EXECUTE ON SCHEMA _SYS_STATISTICS TO RT_COCKPIT_ROLE WITH GRANT OPTION;
GRANT SELECT ON SCHEMA _SYS_STATISTICS TO RT_COCKPIT_ROLE WITH GRANT OPTION;
GRANT DELETE ON SCHEMA _SYS_STATISTICS TO RT_COCKPIT_ROLE WITH GRANT OPTION;
GRANT UPDATE ON SCHEMA _SYS_STATISTICS TO RT_COCKPIT_ROLE WITH GRANT OPTION;
GRANT INSERT ON SCHEMA _SYS_STATISTICS TO RT_COCKPIT_ROLE WITH GRANT OPTION;

GRANT UPDATE ON _SYS_STATISTICS.STATISTICS_SCHEDULE TO RT_COCKPIT_ROLE WITH GRANT OPTION;
GRANT SELECT ON SYS.FULL_SYSTEM_INFO_DUMPS TO RT_COCKPIT_ROLE WITH GRANT OPTION;
GRANT EXECUTE ON SYS.MANAGEMENT_CONSOLE_PROC TO RT_COCKPIT_ROLE WITH GRANT OPTION;

GRANT UPDATE ON _SYS_STATISTICS.STATISTICS_SCHEDULE TO RT_COCKPIT_ROLE WITH GRANT OPTION;
GRANT EXECUTE ON SYS.MANAGEMENT_CONSOLE_PROC TO RT_COCKPIT_ROLE WITH GRANT OPTION;
GRANT EXECUTE ON SYS.FULL_SYSTEM_INFO_DUMP_DELETE TO RT_COCKPIT_ROLE WITH GRANT OPTION;
GRANT EXECUTE ON SYS.FULL_SYSTEM_INFO_DUMP_RETRIEVE TO RT_COCKPIT_ROLE WITH GRANT OPTION;
GRANT EXECUTE ON SYS.FULL_SYSTEM_INFO_DUMP_CREATE TO RT_COCKPIT_ROLE WITH GRANT OPTION;


-- to open the cockpit and access the tiles 
-- DB Administration, Platform Lifecycle Management; backup 
call GRANT_ACTIVATED_ROLE('sap.hana.admin.roles::Administrator','RT_COCKPIT_ROLE');

-- for SAP HANA System Replication
call GRANT_ACTIVATED_ROLE('sap.hana.admin.cockpit.sysrep.roles::SysRepAdmin','RT_COCKPIT_ROLE');

-- to open the Security tool 
call GRANT_ACTIVATED_ROLE('sap.hana.ide.roles::SecurityAdmin','RT_COCKPIT_ROLE'); 

-- Security Overview
call GRANT_ACTIVATED_ROLE('sap.hana.security.cockpit.roles::DisplaySecurityDashboard','RT_COCKPIT_ROLE'); 

-- User Management
call GRANT_ACTIVATED_ROLE('sap.hana.security.cockpit.roles::EditAssignedRoles','RT_COCKPIT_ROLE');

-- Certificate Management
call GRANT_ACTIVATED_ROLE('sap.hana.security.cockpit.roles::EditCertificateStore','RT_COCKPIT_ROLE');

-- to edit Fiori launchpad application
call GRANT_ACTIVATED_ROLE('sap.hana.uis.db::SITE_DESIGNER','RT_COCKPIT_ROLE'); 

/* REPOSITORY privileges
SQL Syntax */

GRANT REPO.EXPORT TO RT_REPOSITORY_ROLE;
GRANT REPO.IMPORT TO RT_REPOSITORY_ROLE;
GRANT REPO.MAINTAIN_DELIVERY_UNITS TO RT_REPOSITORY_ROLE;
/* Erroring out */
--GRANT REPO.WORK_IN_FOREIGN_WORKSPACEGRANT TO RT_REPOSITORY_ROLE;

GRANT REPO.CONFIGURE TO RT_REPOSITORY_ROLE;
GRANT REPO.MODIFY_CHANGE TO RT_REPOSITORY_ROLE;
GRANT REPO.MODIFY_OWN_CONTRIBUTION TO RT_REPOSITORY_ROLE;
GRANT REPO.MODIFY_FOREIGN_CONTRIBUTION TO RT_REPOSITORY_ROLE;

/* SYSTEM privileges
SQL Syntax */

GRANT ADAPTER ADMIN TO RT_SYSTEM_ROLE;
GRANT AGENT ADMIN TO RT_SYSTEM_ROLE;
GRANT ATTACH DEBUGGER TO RT_SYSTEM_ROLE;
GRANT AUDIT ADMIN TO RT_SYSTEM_ROLE;
GRANT AUDIT OPERATOR TO RT_SYSTEM_ROLE;
GRANT SSL ADMIN TO RT_SYSTEM_ROLE;
GRANT CREATE SCHEMA TO RT_SYSTEM_ROLE;
GRANT BACKUP ADMIN TO RT_SYSTEM_ROLE;
GRANT BACKUP OPERATOR TO RT_SYSTEM_ROLE;
GRANT CATALOG READ TO RT_SYSTEM_ROLE;
GRANT CERTIFICATE ADMIN TO RT_SYSTEM_ROLE;
GRANT CREATE REMOTE SOURCE TO RT_SYSTEM_ROLE;
GRANT CREATE STRUCTURED PRIVILEGE TO RT_SYSTEM_ROLE;
GRANT CREDENTIAL ADMIN TO RT_SYSTEM_ROLE;

GRANT DATA ADMIN TO RT_SYSTEM_ROLE;
/* Erroring out */
--GRANT DATABASE ADMIN TO RT_SYSTEM_ROLE;
GRANT EXPORT, IMPORT TO RT_SYSTEM_ROLE;
GRANT EXTENDED STORAGE ADMIN TO RT_SYSTEM_ROLE;
GRANT INIFILE ADMIN TO RT_SYSTEM_ROLE;
GRANT LICENSE ADMIN TO RT_SYSTEM_ROLE;
GRANT LOG ADMIN TO RT_SYSTEM_ROLE;
GRANT MONITOR ADMIN TO RT_SYSTEM_ROLE;
GRANT OPTIMIZER ADMIN TO RT_SYSTEM_ROLE;

GRANT RESOURCE ADMIN TO RT_SYSTEM_ROLE;
GRANT ROLE ADMIN TO RT_SYSTEM_ROLE;
GRANT SAVEPOINT ADMIN TO RT_SYSTEM_ROLE;
GRANT SCENARIO ADMIN TO RT_SYSTEM_ROLE;
GRANT SERVICE ADMIN TO RT_SYSTEM_ROLE;
GRANT SESSION ADMIN TO RT_SYSTEM_ROLE;
GRANT SSL ADMIN TO RT_SYSTEM_ROLE;
GRANT STRUCTUREDPRIVILEGE ADMIN TO RT_SYSTEM_ROLE;

GRANT TENANT ADMIN TO RT_SYSTEM_ROLE;
GRANT TABLE ADMIN TO RT_SYSTEM_ROLE;
GRANT TRACE ADMIN TO RT_SYSTEM_ROLE;
GRANT TRUST ADMIN TO RT_SYSTEM_ROLE;
GRANT USER ADMIN TO RT_SYSTEM_ROLE;
GRANT VERSION ADMIN TO RT_SYSTEM_ROLE;
GRANT WORKLOAD ANALYZE ADMIN TO RT_SYSTEM_ROLE;
GRANT WORKLOAD CAPTURE ADMIN TO RT_SYSTEM_ROLE;
GRANT WORKLOAD REPLAY ADMIN TO RT_SYSTEM_ROLE;
GRANT EXECUTE ON "SYS"."REPOSITORY_REST" TO RT_SYSTEM_ROLE;
GRANT EXECUTE ON "PUBLIC"."GRANT_ACTIVATED_ROLE" TO RT_SYSTEM_ROLE; 
GRANT EXECUTE ON "PUBLIC"."REVOKE_ACTIVATED_ROLE" TO RT_SYSTEM_ROLE; 

-- How to assign privileges to sap hana administrator users?
/* Grant all Roles to the 
final Administrator role
then to the user
SQL Syntax */

GRANT RT_BACKUP_ROLE TO RT_ADMINISTRATOR_ROLE;
GRANT RT_MONITOR_ROLE TO RT_ADMINISTRATOR_ROLE;
GRANT RT_COCKPIT_ROLE TO RT_ADMINISTRATOR_ROLE;
GRANT RT_REPOSITORY_ROLE TO RT_ADMINISTRATOR_ROLE;
GRANT RT_SYSTEM_ROLE TO RT_ADMINISTRATOR_ROLE;

GRANT RT_ADMINISTRATOR_ROLE TO snelluri;
